/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomNavigation: typeof import('./src/components/BottomNavigation.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    EmptyPost: typeof import('./src/components/EmptyPost.vue')['default']
    ImageScale: typeof import('./src/components/ImageScale.vue')['default']
    MidHeader: typeof import('./src/components/MidHeader.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PostButton: typeof import('./src/components/PostButton.vue')['default']
    PostMessage: typeof import('./src/components/PostMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./src/components/Sider.vue')['default']
    SiteLogo: typeof import('./src/components/SiteLogo.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
