/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomNavigation: typeof import('./src/components/BottomNavigation.vue')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    DeleteUserBtn: typeof import('./src/components/DeleteUserBtn.vue')['default']
    EmptyPost: typeof import('./src/components/EmptyPost.vue')['default']
    ImageScale: typeof import('./src/components/ImageScale.vue')['default']
    LilProfileBtn: typeof import('./src/components/LilProfileBtn.vue')['default']
    MidHeader: typeof import('./src/components/MidHeader.vue')['default']
    Navigation_unuse: typeof import('./src/components/Navigation_unuse.vue')['default']
    PanelCloseButton: typeof import('./src/components/PanelCloseButton.vue')['default']
    PostButton: typeof import('./src/components/PostButton.vue')['default']
    PostMessage: typeof import('./src/components/PostMessage.vue')['default']
    PostMessageSkeleton: typeof import('./src/components/PostMessageSkeleton.vue')['default']
    PostPanel: typeof import('./src/components/PostPanel.vue')['default']
    PwdInputIcon: typeof import('./src/components/PwdInputIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./src/components/Sider.vue')['default']
    Sider2: typeof import('./src/components/Sider2.vue')['default']
    SignInButton: typeof import('./src/components/SignInButton.vue')['default']
    SignUpButton: typeof import('./src/components/SignUpButton.vue')['default']
    SiteLogo_unuse: typeof import('./src/components/SiteLogo_unuse.vue')['default']
    SwitchSunOrMoon: typeof import('./src/components/SwitchSunOrMoon.vue')['default']
    TextInput: typeof import('./src/components/TextInput.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    Upscayl: typeof import('./src/components/Upscayl.vue')['default']
  }
}
